wizard progress tracker
ruifang/kitchensink-ui pull request #45
Opened 2022-10-19 18:05 UTC by jgabrielgv

2022-10-19 21:04 UTC, aartaviab approved these changes

2022-10-20 15:51 UTC, ruifang requested changes

2022-10-20 15:51 UTC, ruifang commented on projects/components/src/lib/wizard-progress-tracker/wizard-progress-tracker.component.ts
> +  @Output() notifyStepSelected = new EventEmitter<WizardStepLink>();
`changeStep` to follow naming convention

2022-10-20 15:51 UTC, ruifang commented on projects/components/src/lib/wizard-progress-tracker/wizard-progress-tracker.component.ts
> +export class WizardProgressTrackerComponent {
Can we rename this to ProgressTrackerComponent please? Just trying to shorten it and less specific to wizard

2022-10-20 17:45 UTC, ruifang approved these changes

2022-10-20 17:45 UTC, merged