Feature/cfg 287 improve handling of invalid date in mz datetime
ruifang/kitchensink-ui pull request #51
Opened 2023-03-21 15:43 UTC by Paul-Free

2023-03-23 21:54 UTC, ruifang requested changes

2023-03-23 21:54 UTC, ruifang commented on projects/components/src/lib/date-time/date-time.component.ts
> +  date: Date | undefined | null;
The tab width in this PR looks different. Do you have prettier extension installed? We'll want to use that to format files in this project.

2023-03-23 21:56 UTC, ruifang requested changes

2023-03-23 21:56 UTC, ruifang commented on projects/components/src/lib/date-time/date-time.component.ts
> +  private tempTime: string | undefined | null = null;
What are the tempDate and tempTime for?

2023-03-23 22:07 UTC, ruifang commented on projects/components/src/lib/date-time/date-time.component.ts
> +  private tempTime: string | undefined | null = null;
Looks like they were already here, so ignore my question.

2023-03-31 20:50 UTC, eb-g3dg5 approved these changes

2023-04-10 17:52 UTC, SubjectiveReality commented on projects/components/src/lib/date-time/date-time.component.spec.ts
> +        }));
a new test case or two could be added, like when deleting part of the datetime

2023-04-25 03:51 UTC, SubjectiveReality approved these changes

2023-04-25 03:51 UTC, SubjectiveReality commented on projects/components/src/lib/date-time/date-time.component.spec.ts
> +    dateTime: Date | undefined | null;
no null, just undefined as discovered in TS docs https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined

2023-04-25 03:51 UTC, SubjectiveReality commented on projects/components/src/lib/date-time/date-time.component.ts
> +    time: string | undefined | null;
revert these to just undefined no null, per TS docs https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined

2023-04-25 03:51 UTC, SubjectiveReality commented on projects/components/src/lib/date-time/date-time.component.spec.ts
> +    dateTime: Date | undefined | null;
done

2023-04-25 03:51 UTC, SubjectiveReality commented on projects/components/src/lib/date-time/date-time.component.ts
> +    time: string | undefined | null;
done

2023-04-25 20:12 UTC, ruifang approved these changes

2023-04-25 20:13 UTC, merged